; PlatformIO Project Configuration File

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:desktop]
platform = native

; Tell the builder to compile the project's `src` folder for the tests.
test_build_project_src = yes

; Tell the compiler to look in our test folder for mocked headers first.
build_flags = -I test/test_desktop
