; PlatformIO Project Configuration File

[platformio]
default_envs = esp32dev

[env]
; This is a base environment to hold shared settings for all esp32 boards
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp32dev]
; This is the PURE application environment.
; It inherits from [env] and has no test settings.

[env:hardware]
; This is our dedicated hardware test environment.
extends = env:esp32dev
test_framework = unity
test_build_src = yes
test_ignore = test/test_desktop
; Build all files in src/ EXCEPT for main.cpp for the test firmware.
build_src_filter = +<*> -<main.cpp>

[env:desktop]
; This is our native desktop unit testing environment.
platform = native
test_build_src = yes
build_flags = -I test/test_desktop
test_ignore = test/test_hardware
; Exclude main.cpp from the desktop build as well for consistency.
build_src_filter = +<*> -<main.cpp>
